version: '3'

services:
  db:
    container_name: user_file_db
    build: db/.
    env_file:
      - db/db.env
    networks:
      - project
  
  app:
    container_name: SecureWebApp
    build: app/.
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - project

networks:
  project: